### ISSUE TITLE
Random interity related issue

### ISSUE THREAD

**Issue by baaltommysu** [OpenAttestation/OpenAttestation#31]
Hi I am running OpenAttestation v1.7 in a CentOS machine. Sometimes I got the following error which will give back 'untrusted' result.

I am running a periodic task that will poll the integrity report of a target platform every 15 seconds, and it has been running about one month. 

This behaviour is quite random, I have no clue why and how this error happens. Can anyone give me a hint?

Thanks in advance. 
Tao

PS: here is the log from catalina.out when the error happens:

```
resource requestId:PollHostsRequestIdDC67ED50BA8A41CCC44A92A4838D8B5E
getRequestsByReqId requestId:PollHostsRequestIdDC67ED50BA8A41CCC44A92A4838D8B5E
dao requestId:PollHostsRequestIdDC67ED50BA8A41CCC44A92A4838D8B5E
20/Nov/2015 15:18:45 FATAL - gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:173)
	at gov.niarl.hisAppraiser.integrityReport.HisReportUtil.submitReport(HisReportUtil.java:342)
	at gov.niarl.sal.webservices.hisWebService.server.HisWebService.postIntegrityReport(HisWebService.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:471)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at gov.niarl.hisAppraiser.integrityReport.HisReportData.getQuote(HisReportData.java:86)
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:171)
	... 35 more
- gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:173)
	at gov.niarl.hisAppraiser.integrityReport.HisReportUtil.submitReport(HisReportUtil.java:342)
	at gov.niarl.sal.webservices.hisWebService.server.HisWebService.postIntegrityReport(HisWebService.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:471)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at gov.niarl.hisAppraiser.integrityReport.HisReportData.getQuote(HisReportData.java:86)
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:171)
	... 35 more
gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:173)
	at gov.niarl.hisAppraiser.integrityReport.HisReportUtil.submitReport(HisReportUtil.java:342)
	at gov.niarl.sal.webservices.hisWebService.server.HisWebService.postIntegrityReport(HisWebService.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:471)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at gov.niarl.hisAppraiser.integrityReport.HisReportData.getQuote(HisReportData.java:86)
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:171)
	... 35 more
Nov 20, 2015 3:18:45 PM com.sun.xml.ws.server.sei.EndpointMethodHandler invoke
SEVERE: gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.lang.RuntimeException: gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.sal.webservices.hisWebService.server.HisWebService.postIntegrityReport(HisWebService.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:471)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:173)
	at gov.niarl.hisAppraiser.integrityReport.HisReportUtil.submitReport(HisReportUtil.java:342)
	at gov.niarl.sal.webservices.hisWebService.server.HisWebService.postIntegrityReport(HisWebService.java:113)
	... 33 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at gov.niarl.hisAppraiser.integrityReport.HisReportData.getQuote(HisReportData.java:86)
	at gov.niarl.hisAppraiser.integrityReport.HisReportValidator.<init>(HisReportValidator.java:171)
	... 35 more

```

**Comment by baaltommysu** [comment]
An update, it seems to be a problem from the attested platform, I saw in the OAT.log in the attested platform shows, getQuote timeout, log in the end. But it should not be a problem of continuous attestation requests, because the OAT.log also shows Do_nothing between each send report actions. And it only happens every now and then, every time it has TPM quote timeout error, it will resume working correctly in the next or second next attestation request. 

Any clue?

Thank you in advance.

```
Action:DO_NOTHING
Action:DO_NOTHING
Action:DO_NOTHING
Action:SEND_REPORT
Quote type = 1
TPM Quote interface timeout, process aborted.  Unable to capture quote.
Sending integrity report
java.lang.Exception: Web service error: gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.his.StandaloneHIS.sendIntegrityReport(StandaloneHIS.java:1935)
	at gov.niarl.his.StandaloneHIS.checkIntegrity(StandaloneHIS.java:828)
	at gov.niarl.his.StandaloneHIS.dynamicPoll(StandaloneHIS.java:667)
	at gov.niarl.his.StandaloneHIS.main(StandaloneHIS.java:437)
Action:DO_NOTHING
Action:SEND_REPORT
Quote type = 1
TPM Quote interface timeout, process aborted.  Unable to capture quote.
Sending integrity report
java.lang.Exception: Web service error: gov.niarl.hisAppraiser.integrityReport.HisReportException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at gov.niarl.his.StandaloneHIS.sendIntegrityReport(StandaloneHIS.java:1935)
	at gov.niarl.his.StandaloneHIS.checkIntegrity(StandaloneHIS.java:828)
	at gov.niarl.his.StandaloneHIS.dynamicPoll(StandaloneHIS.java:667)
	at gov.niarl.his.StandaloneHIS.main(StandaloneHIS.java:437)
Action:DO_NOTHING
Action:DO_NOTHING

```

**Comment by ZahediAquino** [comment]
Have you tried this on the latest 2.2 release of OAT?
Does this happen on a single host or all your hosts?

**Comment by baaltommysu** [comment]
Hi, sorry I just notice I have not replied yet. 

I am using the OAT v1.7. 

Actually I have seen this error with some machines, not only just one machine.
But after some time this error will disappear even if there is nothing changed. I am thinking this could be a problem of the trousers service or the hardware of the TPM?
