### ISSUE TITLE
Unable to connect to Trust Agent on ...

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#34]
when I add new host to Host Management at TrustDashBoard, following error message I met.

Unable to connect to Trust Agent on '172.25.0.171:9999'. Timed out after 3 seconds [AS_TRUST_AGENT_CONNNECT_TIMED_OUT] [1024]

to configure, 
Host Name: agent's IP address 
Host IP Address: agent's IP address
Host Port: 9999 (by default)
OEM Vendor: custom-defined
BIOS Info: custom-defined
OS-VMM Info: custom-defined
------------
And tagent status says as follow:

root@oat-client:/sys# service tagent status
● tagent.service - SYSV: Intel TrustAgent Service
   Loaded: loaded (/etc/init.d/tagent)
   Active: active (exited) since 수 2015-12-16 12:05:47 KST; 30s ago
  Process: 5986 ExecStart=/etc/init.d/tagent start (code=exited, status=0/SUCCESS)

12월 16 12:05:47 oat-client tagent[5986]: /etc/intel/cloudsecurity/PrivacyCA.cer exists
12월 16 12:05:47 oat-client tagent[5986]: /etc/intel/cloudsecurity/hisprovisioner.pr...ts
12월 16 12:05:47 oat-client tagent[5986]: 5759
12월 16 12:05:47 oat-client tagent[5986]: Trust Agent is already running
Hint: Some lines were ellipsized, use -l to show in full.

===========
where should I check again?

**Comment by ZahediAquino** [comment]
Check the trustagent log, should be in:
/var/log/tangent.log
Or
/var/log/trust agent/tangent.log

Paste as much content from when the error occurs.

Have you checked the ports for the trust agent are open on the host also?

**Comment by ZahediAquino** [comment]
Correction:
/var/log/tagent.log
Or
/var/log/trust agent/tagent.log

**Comment by mipsan** [comment]
1. service port: 9999 / 9998 allowed
2. I attach /var/log/tagent.log:
----------
root@oat-client:/home/debian# cat /var/log/tagent.log
TAConfig [system]: app.path=/opt/intel/cloudsecurity/trustagent
TAConfig [system]: debug=true
TAConfig [system]: secure.port=null
TAConfig [system]: nonsecure.port=null
55 [main] INFO com.intel.mountwilson.common.TAConfig - Reading property file /trustagent.properties
TAConfig os.name=Linux
TAConfig [file:/etc/intel/cloudsecurity/trustagent.properties]: app.path=/opt/intel/cloudsecurity/trustagent
TAConfig [file:/etc/intel/cloudsecurity/trustagent.properties]: debug=false
TAConfig [file:/etc/intel/cloudsecurity/trustagent.properties]: secure.port=9999
TAConfig [file:/etc/intel/cloudsecurity/trustagent.properties]: nonsecure.port=9998
TAConfig [default]: app.path=.
TAConfig [default]: debug=false
TAConfig [default]: secure.port=9999
TAConfig [default]: nonsecure.port=9998
TAConfig [composite]: app.path=/opt/intel/cloudsecurity/trustagent
TAConfig [composite]: debug=true
TAConfig [composite]: secure.port=9999
TAConfig [composite]: nonsecure.port=9998
ResourceFinder os.name=Linux
73 [main] WARN com.intel.mountwilson.common.Config - Home folder. Using /etc/intel/cloudsecurity
looking for /opt/intel/cloudsecurity/trustagent/config/logging.properties
Could not initiate the logging. Log will be output to console.
235 [main] INFO com.intel.mountwilson.trustagent.TrustAgent - Data folder was not there created : /etc/intel/cloudsecurity/data/
12월 16, 2015 11:56:50 오전 com.intel.mountwilson.his.helper.ProvisionTPM takeOwnership
정보: Home folder : /etc/intel/cloudsecurity/
12월 16, 2015 11:56:50 오전 com.intel.mountwilson.his.helper.ProvisionTPM takeOwnership
정보: owner authentication is char formatted
12월 16, 2015 11:56:50 오전 com.intel.mountwilson.his.helper.ProvisionTPM takeOwnership
정보: ecStorageFileName:/opt/intel/cloudsecurity/trustagent/EC.cer
12월 16, 2015 11:56:50 오전 com.intel.mountwilson.his.helper.ProvisionTPM takeOwnership
정보: Performing TPM provisioning...
12월 16, 2015 11:56:50 오전 gov.niarl.his.privacyca.TpmModule executeVer2Command
정보: Reading properties filefile:/etc/intel/cloudsecurity/TPMModule.properties
12월 16, 2015 11:56:50 오전 com.intel.mountwilson.his.helper.ProvisionTPM takeOwnership
정보: Ownership is already taken :
279 [main] INFO com.intel.mountwilson.trustagent.commands.TakeOwnershipCmd - Take ownership command executed successfully

**Comment by mipsan** [comment]
Zahedi, 
FYI I attach catalina.out log when error comes.
---------------
2015-12-16 18:43:05,885 INFO [http-bio-8080-exec-12] c.i.m.s.SecurityFilter [SecurityFilter.java:45] SecurityFilter >>
org.apache.catalina.session.StandardSessionFacade@1d7fc3e9----/getData/saveNewHostInfo.html
true
2015-12-16 18:43:05,886 INFO [http-bio-8080-exec-12] c.i.m.s.SecurityFilter [SecurityFilter.java:58] User is logged in, forwarding request to /getData/saveNewHostInfo.html
2015-12-16 18:43:05,916 INFO [http-bio-8080-exec-12] c.i.m.c.DemoPortalDataController [DemoPortalDataController.java:215] WLMDataController.saveNewHostInfo >>
{"hostId": null, "hostName": "172.25.0.171", "hostIPAddress": "172.25.0.171", "hostPort": "9999", "hostDescription": "", "biosName": "NewMLE1", "biosBuildNo": "v123", "vmmName": "Debian 8.2|KVM", "vmmBuildNo": "v123", "updatedOn": null, "emailAddress": "", "location": null, "oemName": "INTEL"}
dataForNew : HostDetailsEntityVO [hostId=null, hostName=172.25.0.171, hostIPAddress=172.25.0.171, hostPort=9999, hostDescription=, biosName=NewMLE1, biosBuildNo=v123, vmmName=Debian 8.2|KVM, vmmBuildNo=v123, updatedOn=Wed Dec 16 18:43:05 KST 2015, emailAddress=, location=null, oemName=INTEL, vCenterDetails=null]
2015-12-16 18:43:05,957 INFO [http-bio-8181-exec-2] c.i.m.a.h.ASComponentFactory [ASComponentFactory.java:41] Class not found: java.lang.ClassNotFoundException: com.intel.mtwilson.as.premium.PremiumHostBO
2015-12-16 18:43:05,958 INFO [http-bio-8181-exec-2] c.i.m.j.PersistenceManager [PersistenceManager.java:87] PersistenceManager is configured with 1 factories in getEntityManagerFactory
2015-12-16 18:43:05,965 INFO [http-bio-8181-exec-2] c.i.m.j.PersistenceManager [PersistenceManager.java:87] PersistenceManager is configured with 1 factories in getEntityManagerFactory
2015-12-16 18:43:05,976 INFO [http-bio-8181-exec-2] c.i.m.a.b.HostBO [HostBO.java:75] Getting Server Identity.
2015-12-16 18:43:05,977 INFO [http-bio-8181-exec-2] c.i.m.a.h.TrustAgentSecureClient [TrustAgentSecureClient.java:93] TrustAgentSecureClient url(https://172.25.0.171:9999) hostname(172.25.0.171) port(9999)
2015-12-16 18:43:05,977 INFO [http-bio-8181-exec-2] c.i.m.a.h.TrustAgentSecureClient [TrustAgentSecureClient.java:261] Sending Generate Identity
2015-12-16 18:43:09,252 ERROR [http-bio-8080-exec-12] c.i.m.S.DemoPortalServicesImpl [DemoPortalServicesImpl.java:264] Errror While Adding New Host.Unable to connect to Trust Agent on '172.25.0.171:9999'. Timed out after 3 seconds [AS_TRUST_AGENT_CONNNECT_TIMED_OUT]
com.intel.mtwilson.ApiException: Unable to connect to Trust Agent on '172.25.0.171:9999'. Timed out after 3 seconds [AS_TRUST_AGENT_CONNNECT_TIMED_OUT]
        at com.intel.mtwilson.ApiClient.error(ApiClient.java:289)
        at com.intel.mtwilson.ApiClient.content(ApiClient.java:328)
        at com.intel.mtwilson.ApiClient.text(ApiClient.java:348)
        at com.intel.mtwilson.ApiClient.addHost(ApiClient.java:508)
        at com.intel.mountwilson.Service.DemoPortalServicesImpl.saveNewHostData(DemoPortalServicesImpl.java:261)
        at com.intel.mountwilson.controller.DemoPortalDataController.saveNewHostInfo(DemoPortalDataController.java:254)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:473)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:410)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.intel.mountwilson.security.SecurityFilter.doFilter(SecurityFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
2015-12-16 18:43:09,253 ERROR [http-bio-8080-exec-12] c.i.m.c.DemoPortalDataController [DemoPortalDataController.java:260] Unable to connect to Trust Agent on '172.25.0.171:9999'. Timed out after 3 seconds [AS_TRUST_AGENT_CONNNECT_TIMED_OUT] [1024]

**Comment by mipsan** [comment]
Zahedi, 

I reviewed the catalina.out log and found a strange thing.
TrustAgent server is listening on TCP6(IPv6) port. 
However tomcat try to connect IPv4 address '172.25.0.169:9999'. 
Is it correct action? 

screenshot attached: 
![scr](https://cloud.githubusercontent.com/assets/3205851/11859727/39831848-a4b1-11e5-9753-4d97db4ca869.png)

**Comment by mipsan** [comment]
Problem was Port policy at firewall as you advised.

After modification, I encountered another problem as follow:

Trust Agent failed with code '1007' and message 'Trust Agent:  Error while creating identity.' [AS_TRUST_AGENT_ERROR] [1012]

And I attach log files, catalina.out and tagent.log.

Thanks.

[catalina.out.txt](https://github.com/OpenAttestation/OpenAttestation/files/65074/catalina.out.txt)
[tagent.log.txt](https://github.com/OpenAttestation/OpenAttestation/files/65073/tagent.log.txt)

**Comment by mipsan** [comment]
I tried following two jobs to solve error code 1007, but failed.

https://lists.01.org/pipermail/oat-devel/2014-September/000131.html
https://github.com/OpenAttestation/OpenAttestation/issues/8

And now, I'm re-installing client host as 
https://github.com/OpenAttestation/OpenAttestation/issues/22

**Comment by mipsan** [comment]
When you meet this error message,
Trust Agent failed with code '1007' and message 'Trust Agent: Error while creating identity.' [AS_TRUST_AGENT_ERROR] [1012]

clear TPM key at BIOS, and then try to Add Host again. Here, without tpm_takeownership!
