### ISSUE TITLE
ERROR occured while executing the command: mvn clean install -DskipTests=true on ubuntu 14.04

### ISSUE THREAD

**Issue by TahirAhmed916** [OpenAttestation/OpenAttestation#39]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM: Could not find artifact com.intel.mtwilson.maven:mtwilson-maven-package-bin-zip:pom:3.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 9, column 13
[WARNING] 'build.plugins.plugin.version' for pl.project13.maven:git-commit-id-plugin is missing. @ line 28, column 21

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.intel.mtwilson.tbootxm:tbootxm-rpmmio:0.1-SNAPSHOT (/home/server/OpenAttestation/tbootxm-rpmmio/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.intel.mtwilson.maven:mtwilson-maven-package-bin-zip:pom:3.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 9, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact com.intel.mtwilson.maven:mtwilson-maven-package-bin-zip:pom:3.0-SNAPSHOT
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:813)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:495)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.intel.mtwilson.maven:mtwilson-maven-package-bin-zip:pom:3.0-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
	... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.intel.mtwilson.maven:mtwilson-maven-package-bin-zip:pom:3.0-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
	... 28 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by schrotti12** [comment]
I tried to delete the <parent> node and now maven is running. Can't say how far it is working but I#ll report as soon as I get results.

**Comment by ciclismolibre** [comment]
schrotti12, same issue here. Did you finally get the deploy-folder?

**Comment by ZahediAquino** [comment]
What branch are you guys pulling from? What OS are you guys doing this on? is this on a fresh OS image? Please provide more info so we can try to reproduce. Thanks

**Comment by schrotti12** [comment]
Just tried to do it:
OS: Fresh Ubuntu 14.04.4, installed from ISO.
Machine: Virtualbox VM.
Dependencies installed with following command
`apt-get install -y git maven openjdk-7-jdk zip make g++ makeself libbcprov-java`
Added
**"security.provider.11=org.bouncycastle.jce.provider.BouncyCastleProvider"**
to file
**"/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/java.security"**

**Comment by R-Vaishnavi** [comment]
Hi,I am still facing the issue. How did u add the relative path? Is it like this:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd ../maven/mtwilson-maven-package-bin-zip/pom.xml">

**Comment by R-Vaishnavi** [comment]
Found the relative path option. But unable to find the 'deploy' folder. Anyone found a solution for that ?

**Comment by ZahediAquino** [comment]
It's been pointed out that the branch and the latest release tag had the same name 'v2.3', this tag had some issues apparently. Tag 'v2.3' has been deleted, please follow the instructions again and run 'git checkout v2.3', this time the right content should be checked out (from the branch, not the tag)... a new tag for the release was also re-created, it is now called 'v2.3.0' to distinguish it from the branch. Let us know how it goes.
